Document all the reference shapes and their (current) numbering
Ferrite-FEM/Ferrite.jl pull request #688
Opened 2023-04-27 11:36 UTC by fredrikekre

2023-04-27 13:03 UTC, termi-official requested changes
We could also leave a hint for https://ferrite-fem.github.io/FerriteViz.jl/dev/api/#FerriteViz.elementinfo which displays element information interactively.

2023-04-28 06:18 UTC, fredrikekre commented on src/docs.jl
> +1-------2       |
Okay, strange.

2023-04-28 07:07 UTC, fredrikekre commented on src/docs.jl
> + 2 /              2 /             |
Good suggestion, added!

2023-04-28 07:10 UTC, fredrikekre commented
> We could also leave a hint for https://ferrite-fem.github.io/FerriteViz.jl/dev/api/#FerriteViz.elementinfo which displays element information interactively.

Done! :)

2023-04-28 08:59 UTC, termi-official approved these changes
Great and thanks! I went over them once more and I *think* they reflect these docs current implementation.

2023-04-28 09:00 UTC, fredrikekre commented
Thanks for the review!

2023-04-28 09:18 UTC, merged