added interpolation
Ferrite-FEM/Ferrite.jl pull request #701
Opened 2023-05-10 10:13 UTC by JanM12

introduced interpolation Lagrange{2,RefCube,3} to src/interpolations.jl

2023-05-10 10:27 UTC, koehlerson requested changes
need to add the new interpolation to the test suite, see: https://github.com/Ferrite-FEM/Ferrite.jl/blob/master/test/test_interpolations.jl#L3-L36

2023-05-10 10:27 UTC, koehlerson commented on src/interpolations.jl
> +function value(ip::Lagrange{2,RefCube,3}, i::Int, ξ::Vec{2})
```suggestion
function value(ip::Lagrange{2,RefCube,3}, i::Int, ξ::Vec{2})
# see https://defelement.com/elements/examples/quadrilateral-Q-3.html
```

2023-05-11 10:16 UTC, fredrikekre commented
Looks like the tolerance here https://github.com/Ferrite-FEM/Ferrite.jl/blob/ade9292688770f54caaccae6eb1af7e3d712a49e/test/test_interpolations.jl#L106needs to be adjusted (or possibly the long expressions here can be reordered to give a smaller error like what was done in #633, but maybe not possible).

2023-05-11 11:00 UTC, termi-official commented
Give me some more time to think about this adjustment, because I am not really sure about what could break downstream due to such spurious evaluations and what the related thresholds to prevent numerical oscillations are. Also I do not know how these affect the overall assembly precision. Generally speaking we should still be able to reorder the expressions to eliminate errors in the tested delta property (even though it is not trivial).

2023-05-13 17:08 UTC, fredrikekre commented
Perhaps we can BigFloats and truncate to Float64 after evaluation.

2023-05-13 17:35 UTC, termi-official commented
But this will be a big performance hit for the value call then.

2023-05-13 19:41 UTC, fredrikekre commented
Maybe, but it is only called in the constructor.

2023-05-13 19:49 UTC, AbdAlazezAhmed commented
How about using `Rational` ?

2023-05-13 20:29 UTC, termi-official commented
Thanks for this suggestions!

> Maybe, but it is only called in the constructor.

For order 3 (and maybe order 4) this should be fine, but when moving to higher order one quickyl runs into the issue that assembly degrades solver performance quite severly. Here usually matrix-free techniques are deployed which require reevaluation of the basis functions. I think `BigFloat` could hurt performance in this scenario quite a bit. To not delay this PW we can go either way and discuss this in a separate issue/discussion, investigating this in more detail (and maybe gathering some literature on this).


> How about using `Rational` ?

This would certainly fix the tests, but IIRC then general quadrature points are unfortunately Irrational. However, I am happy to get corrected if I am wrong on this.

2023-05-14 05:31 UTC, AbdAlazezAhmed commented
> This would certainly fix the tests, but IIRC then general quadrature points are unfortunately Irrational. However, I am happy to get corrected if I am wrong on this.

You're right. [AccurateArithmetic.jl](https://github.com/JuliaMath/AccurateArithmetic.jl) can be helpful?

2023-05-21 14:58 UTC, termi-official commented
Okay maybe we can bring this over the finish line as follows. We can increase the number of points in the partition of unity test here (points outside the domain should be rejected!)

https://github.com/Ferrite-FEM/Ferrite.jl/blob/1fadc1fc63bf6751e8f56ac1619c40d8a3c87465/test/test_interpolations.jl#L50-L55

and increase the tolerance here https://github.com/Ferrite-FEM/Ferrite.jl/blob/1fadc1fc63bf6751e8f56ac1619c40d8a3c87465/test/test_interpolations.jl#L107 to 1e-14 . This should be reasonably small for now.

Alternatively we can try to overdub the value calls in the tests with Kahan summations, but this might be a bit more work. It think the linked package fails with AD (just skipped over the implementation).

2023-05-26 07:53 UTC, closed without merging