change to well posed NeoHooke
Ferrite-FEM/Ferrite.jl pull request #846
Opened 2023-11-16 09:10 UTC by koehlerson

https://github.com/Ferrite-FEM/Ferrite.jl/issues/844

2023-11-16 09:25 UTC, koehlerson commented
![image](https://github.com/Ferrite-FEM/Ferrite.jl/assets/27497290/b6edbdd1-36bc-4170-abcc-b414c40e9113)
looks quite the same, but `norm(u)` is slightly different, probably to be expected?

2023-11-16 09:43 UTC, koehlerson commented
alternatively in https://onlinelibrary.wiley.com/doi/full/10.1002/nme.4351 another formulation is used which is not normalized. The current one from Wikipedia is normalized (in the sense of $\psi(\boldsymbol{1})=0$)

2023-11-16 11:04 UTC, KnutAM commented
In true Ferrite-spirit: https://www.dealii.org/current/doxygen/deal.II/step_44.html#NeoHookeanmaterials and ref to Holzapfel (2001) therein :)
Perhaps nice to comment in the example that there are different possible formulations for the volumetric part (as is done in the deal.ii example)?

2023-11-16 12:16 UTC, koehlerson commented
Citing a 400 pages book by "see Holzapfel (2001)" is an engineering practice, I'll never understand. The reference is equation (6.138). Within the book, the actual reference is Simo and Miehe (1992) (https://www.sciencedirect.com/science/article/pii/004578259290170O equation 2.37) . The chapter of equation (6.138) talks about "ogden model for compressible rubber-like materials". I can add later a reference to Simo and Miehe for one alternative choice and maybe another statement that this is free of choice as long as it is strictly convex in $J$

2023-11-16 14:42 UTC, KnutAM commented
First of all: Sorry if I made you do a lot of digging now - that was not my intention! 

I think you should implement the (strictly convex, or polyconvex if that suffices) free energy that you prefer. (I agree that Psi(I)=0 is nice). I just thought that the following could be nice

1) Referring to where the model we use is taken from (doesn't have to be the original reference if well-established, could refer to an equation in a book)
2) Commenting that multiple options for the volumetric part exist/can be made (but additional examples/refs are not required IMO as it isn't a theory manual.)

2023-11-16 20:41 UTC, koehlerson commented
> First of all: Sorry if I made you do a lot of digging now - that was not my intention!

Sorry if the message was perceived that way. It was meant more in the direction that I'd rather see in our docs some precise citation, especially since this tutorial may be the template for beginners (including me back then). The rant was more about the general situation in engineering publications where I encounter often the same.

> 
> I think you should implement the (strictly convex, or polyconvex if that suffices) 

if it's strictly convex in $J$ then $\psi(\boldsymbol{F})$ becomes polyconvex w.r.t. $\boldsymbol{F}$ which is a key ingredient of well posedness. That's why you want the strictly convex term in $J$.

> 
>     1. Referring to where the model we use is taken from (doesn't have to be the original reference if well-established, could refer to an equation in a book)

Yeah that's fine for me. Will do that tomorrow.

> 
>     2. Commenting that multiple options for the volumetric part exist/can be made (but additional examples/refs are not required IMO as it isn't a theory manual.)

Yeah I was planning some `note !!!` or the like

2023-11-24 08:11 UTC, lijas commented
Perhaps this is a stupid questions, but does not chaning the potentional mean that it is no longar a Neo-hookean model? Or are there many types neo-hookean models? 
Also, the original formulation is only breaks down for really large deformation (J=10), right?

2023-11-24 08:21 UTC, KnutAM commented
> Perhaps this is a stupid questions, but does not chaning the potentional mean that it is no longar a Neo-hookean model? Or are there many types neo-hookean models?

To my understanding, the true/original "NeoHooke" model is incompressible, but can be extended to a compressible formulation for which there are different variants of the volumetric contribution.

2023-11-24 08:32 UTC, lijas commented
Ok thanks for clarifying. The original NeoHooke model would then require to be used with taylor-hood (displacement preasure) elements, I guess?

2023-11-24 09:19 UTC, koehlerson commented
> Ok thanks for clarifying. The original NeoHooke model would then require to be used with taylor-hood (displacement preasure) elements, I guess?

Neo Hooke is just $C_1 (I_1 - 3)$ and if you compute this without a pressure formulation you can increase the volume freely leading to many (infinite I guess) solutions. So either a pressure field is incorporated for the incompressible model or you add some well posed penalty terms as we have in the example here. But it's definitely worth to mention that there is no such thing as "the" compressible Neo Hooke model

2023-11-30 00:52 UTC, termi-official requested changes
Hyperelasticity docs are broken on the deploy. I left a commen where this might come from. Can you check locally?

2023-11-30 00:52 UTC, termi-official commented on docs/src/literate-tutorials/hyperelasticity.jl
> +#    The Neo-Hooke model is only a well defined terminology in the incompressible case.
I think you need one more space here for the indentation.

2023-12-01 10:33 UTC, KnutAM reviewed
Great job fixing this and adding more details on neo-Hookean models with proper references!

2023-12-03 03:31 UTC, merged